# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-07 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('NL', 'Netherlands'), ('DK', 'Denmark'), ('ES', 'Spain'), ('IT', 'Italy'), ('SE', 'Sweden')], max_length=2)),
                ('city', models.CharField(max_length=500)),
            ],
        ),
    ]
